name: NexoPolarBridge
version: ${version}
main: dev.slne.surf.nexopolarbridge.NexoPolarBridge
api-version: '1.21'
folia-supported: true

dependencies:
  server:
    Nexo:
      required: true
      load: BEFORE
      join-classpath: true